### Laboratorium 3  
- web scrapping [requests, beatiful soup, json]

### Requests

In [7]:
import requests as re

req = re.get('https://www.forbes.pl/diamenty/najszybciej-rozwijajace-sie-firmy-w-wojewodztwie-mazowieckim-w-2020-roku/vbbfems')

if req.status_code == 200:
    print('Strona pobrana')
else:
    print('Błąd')

Strona pobrana

In [12]:
req.headers

{'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '75012', 'Connection': 'keep-alive', 'Server': 'Ring Publishing - Accelerator', 'Date': 'Sun, 31 Oct 2021 14:06:41 GMT', 'Vary': 'Accept-Encoding, user-agent', 'x-dns-prefetch-control': 'off', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=0', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache', 'etag': '"75012-90d9fde38c833781"', 'content-encoding': 'gzip', 'content-security-policy-report-only': "default-src https: data: blob: 'unsafe-inline' 'unsafe-eval' ; report-uri https://events.ocdn.eu/v2/csp-report?_ac=events&_fv=www.forbes.pl::PROD", 'link': '<https://www.googletagmanager.com>; rel=preconnect, <https://www.google-analytics.com>; rel=preconnect, <https://ocdn.eu>; rel=preconnect, <https://events.ocdn.eu>; rel=preconnect', 'set-cookie': 'acc_segment=8; Path=/; Max-Age=604800; Secure', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 cb4c4a25e4ef534686959996782c8476.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P2', 'X-Amz-Cf-Id': '7R17Ub-aM2kbdFMN5JiOdylhbLB4KoRmmG8tW-gEXKQwO_BVOf0OeA=='}

In [11]:
#modyfikacja user-agent
req.request.headers

{'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

In [14]:
print(req.text)

<!DOCTYPE html>
<html lang="pl">

<head><script>/* <![CDATA[ */ ringDataLayer = {"context":{"variant":{"accelerator":"d3d3LmZvcmJlcy5wbDo6UFJPRA=="},"publication_structure":{"root":"WWW_FORBES_PL","path":"DIAMENTY/ARTICLE"}},"content":{"object":{"type":"story","kind":"article","id":"7030dff3-7ef1-4878-ade5-8086e115e79d"},"part":1,"publication":{"point":{"id":"vbbfems"}},"source":{"system":"ring_content_space","id":"5e7a324a-2672-42a4-a66e-ad5d1b9604df"}}}; /* ]]> */</script><script>/* <![CDATA[ */ accConf = {"rum":{"tid":"EA-1746213","boot":"disable","cookieInfo":0,"pageType":"HTML"},"gtm":{"id":["GTM-KP6VZF"],"pageType":"HTML"},"events":{"endpointPaths":["/a8f4d8cd95e164917035b64b867a45dd"]}}; /* ]]> */</script>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KP6VZF');</script>
<!-- End Google Tag Manager -->

    <title>Najszybciej rozwijające się firmy w województwie mazowieckim - w 2020 roku  - Diamenty - Forbes.pl</title>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=yes, maximum-scale=1">



<script src="https://s-eu-1.pushpushgo.com/js/60e574da97d09e85115cef9e.js" async></script>


    <link rel="preload" href="https://ocdn.eu/forbes/fonts/Merriweather-LightItalic.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="https://ocdn.eu/forbes/fonts/Merriweather-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="https://ocdn.eu/forbes/fonts/Merriweather-Bold.woff2" as="font" type="font/woff2" crossorigin>






<link rel="preload" href="//ocdn.eu/ucs/static/UCS2Piano/5fd674d8eb489403f8d97b9aed46d796/build/standard/detail_forbes_ucs2.css" as="style" />
<link rel="stylesheet" href="//ocdn.eu/ucs/static/UCS2Piano/5fd674d8eb489403f8d97b9aed46d796/build/standard/detail_forbes_ucs2.css" />

<noscript>
    <link href="//ocdn.eu/ucs/static/UCS2Piano/5fd674d8eb489403f8d97b9aed46d796/build/standard/main_nojs.css" rel="stylesheet" />
</noscript>

<link rel="manifest" href="//ocdn.eu/ucs/static/UCS2Piano/5fd674d8eb489403f8d97b9aed46d796/forbes/manifest.json">
<link rel="preconnect" href="https://adservice.google.com">
<link rel="preconnect" href="https://ajax.googleapis.com">
<link rel="preconnect" href="https://authorisation.grupaonet.pl">
<link rel="preconnect" href="https://buy.tinypass.com">
<link rel="preconnect" href="https://cdn.ampproject.org">
<link rel="preconnect" href="https://cdn.tinypass.com">
<link rel="preconnect" href="https://sgqcvfjvr.onet.pl">
<link rel="preconnect" href="https://csr.onet.pl">
<link rel="preconnect" href="https://events.ocdn.eu">
<link rel="preconnect" href="https://experience.tinypass.com">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://googleads.g.doubleclick.net">
<link rel="preconnect" href="https://kropka.onet.pl">
<link rel="preconnect" href="https://ls.hit.gemius.pl">
<link rel="preconnect" href="https://mab.chartbeat.com">
<link rel="preconnect" href="https://mabping.chartbeat.net">
<link rel="preconnect" href="https://ocdn.eu">
<link rel="preconnect" href="https://onet.hit.gemius.pl">
<link rel="preconnect" href="https://pagead2.googlesyndication.com">
<link rel="preconnect" href="https://ping.chartbeat.net">
<link rel="preconnect" href="https://securepubads.g.doubleclick.net">
<link rel="preconnect" href="https://tagger.opecloud.com">
<link rel="preconnect" href="https://tpc.googlesyndication.com">
<link rel="preconnect" href="https://www.googletagmanager.com">
<link rel="preconnect" href="https://www.googletagservices.com">


<script data-static-amd-map="{&quot;embeddedapp&quot;:&quot;https://ocdn.eu/paas-static/template-engine/162d5140a65ebc0fa2e96da195a4eb9b/build&quot;,&quot;tabele&quot;:&quot;https://ocdn.eu/paas-static/template-engine/08725d11c5641c65d7f9985ecb7b86c0/build&quot;,&quot;layerglass&quot;:&quot;https://ocdn.eu/paas-static/template-engine/05afb91f43a4cacccad6959d895ac7ed/build&quot;,&quot;dailyneeds&quot;:&quot;https://ocdn.eu/paas-static/template-engine/fbc3bd59219c65f9c312840c9743c691/build&quot;,&quot;vendor&quot;:&quot;https://ocdn.eu/paas-static/template-engine/e664b902675175d7b4ea37dc48134f31/build&quot;,&quot;adsinit&quot;:&quot;https://ty0lm9uz.onet.pl/e1BrazhrODR9/build&quot;,&quot;uststd&quot;:&quot;https://ocdn.eu/paas-static/template-engine/f066ddd0af5c65555c5ff1273876e4f9/build&quot;,&quot;pulsembed&quot;:&quot;https://pulsembed.eu/amd/1.0.5/build&quot;,&quot;quizapp&quot;:&quot;https://ocdn.eu/paas-static/template-engine/4bf940d37e48f3548c375c519c69e1da/build&quot;,&quot;local&quot;:&quot;//ocdn.eu/ucs/static/UCS2Piano/5fd674d8eb489403f8d97b9aed46d796/build&quot;}">



//a
/*
Available via the MIT or new BSD license.
see: http://github.com/szagi3891/AMDLoader for details
version 2.7
*/
(function(){function d(a,b){C("err",a,b);(function(a,b){var d="amdLoader: errorNumber: "+a;"string"===typeof b&&""!==b&&(d+=": "+b);var l=Error(d);setTimeout(function(){throw l;},0)})(a,b)}function w(a,b){C("warn",a,b)}function v(a,b){C("info",a,b)}function C(a,b,d){a={type:"warn",num:b,caption:d,time:(new Date).getTime()-I};z.push(a)}function t(a,b,g,m,h,l){function e(f){Object.defineProperty(a,b,{get:function(){!0===m&&w(h+"->1",l);return g},set:function(){d(h+"->2",l)},configurable:f})}try{e(!1)}catch(q){try{e(!0)}catch(f){a[b]=
g}}}function r(a,b){null===s?d(3):A(a,b,24.1)&&(0<a.length?y.requireModules(a,b):d(24.2))}function F(a,b,g){null===s?w(4):1===arguments.length?A([],a,"25.1")&&y.define([],a):2===arguments.length?"string"===typeof a&&"function"===typeof b?(u(a)?w("25.3",a):w("25.3"),y.define([],b)):A(a,b,"25.2")&&y.define(a,b):3===arguments.length?(u(a)?w("25.4",a):w("25.4"),A(b,g,"25.4")&&y.define(b,g)):d("25.5")}function A(a,b,g){if(G(a)){if("function"===typeof b)return!0;d(g+"->1")}else d(g+"->2");return!1}function J(a){var b=
!1,g=!1,m=null,h=null,l=H(!1);return{isDefine:function(){return b},setDefine:function(e,q){!0===g?d(45,a):!1===b?(b=!0,m=e,setTimeout(function(){y.requireModulesWithModuleBase(a,e,function(){var b=Array.prototype.slice.call(arguments,0);try{h=q.apply(null,b)}catch(e){d(14,a+" -> "+e);return}l.exec([h])})},0)):d(15,a)},getDeps:function(){return!0===b?m:[]},get:function(a){l.add(a)},closeDefine:function(){g=!0;!1===b&&(b=!0,l.exec([void 0]))}}}function K(a){function b(b,e,g){if(0<b.length&&"."===b[0])!0===
g&&d(16,b);else{if("https://"===b.substr(0,8)||"http://"===b.substr(0,7)||"//"===b.substr(0,2))return b;for(var f in a)if(0===b.indexOf(f+"/")){f=b.replace(f,a[f]);if(b!==f)return u(e)?f+"."+e:f;!0===g&&d(17,b);return}!0===g&&d(18,b)}}function g(b){document.getElementsByTagName("head")[0].appendChild(b)}function m(b,a){function d(){!0!==x&&(!0===f&&(c.readyState=void 0),x=!0,a(c))}var f=!1,x=!1,c=document.createElement("script");c.type="text/javascript";c.src=b;c.onload=d;c.async=!0;c.defer=!0;!0===
f&&(c.readyState="interactive");c.onreadystatechange=function(){"loaded"!==c.readyState&&"complete"!==c.readyState||d()};return c}var h={};return{load:function(b,a){if(u(b)){if(!(b in h)){var d=m(b,function(){h[b].query.exec([])});h[b]={script:d,query:H(!0)};g(d)}h[b].query.add(a)}},getActialLoading:function(){for(var b in h)if("interactive"===h[b].script.readyState)return b;return null},resolvePath:b,isLoad:function(a){a=b(a,"js",!0);return u(a)&&a in h?h[a].query.isExec():!1},isSpecified:function(a){a=
b(a,"js",!1);return u(a)&&a in h?!0:!1}}}function B(a,b){for(var d=0;d<a.length;d++)b(a[d])}function u(a){return"string"===typeof a&&""!==a}function H(a){function b(){if(!0===m)for(;0<h.length;)!0===a?h.shift().apply(null,l):g(h.shift())}function g(b){setTimeout(function(){b.apply(null,l)},0)}var m=!1,h=[],l=null;return{exec:function(a){G(a)?!1===m?(m=!0,l=a,b()):d(19):d(20)},add:function(a){"function"===typeof a?(h.push(a),b()):d(21)},isExec:function(){return m}}}function D(){return document.currentScript&&
"function"===typeof document.currentScript.getAttribute?document.currentScript:null}var G=function(){return"function"===typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"[object Array]"===Object.prototype.toString.call(a)}}(),y=function(){function a(a,b){var c=a.split("/");2>c.length?d(5,a):(c.pop(),b(c.join("/")))}function b(a,b){var c=a.split("/"),n=b.split("/");if(0<n.length)if("."===n[0]){var k=[];B(c,function(a){k.push(a)});B(n,function(a){"."!==a&&k.push(a)});c=k.join("/");
if(0===c.indexOf(a))return c;d(6,a+" , "+b+" -> "+c)}else return b;else d(7,b)}function g(a,b){function c(){if(!1===n){for(var c=[],E=0;E<a.length;E++){var d=a[E];if(!0===k[d].isInit)c.push(k[d].value);else return}n=!0;"function"===typeof b&&b.apply(null,c)}}var n=!1,k={};B(a,function(a){a in k?d(10,a):(k[a]={isInit:!1,value:null},m(a,function(b){var n=k[a];!1===n.isInit?(n.isInit=!0,n.value=b,c()):d(11,a)}))});c()}function m(a,b){l=!0;var c=s.resolvePath(a,"js",!0);c in e||(e[c]=J(a),s.load(c,function(){if(c in
e){for(;0<q.length;){var a=q.pop();h(c,a.deps)?d(12.1,c):e[c].setDefine(a.deps,a.define)}e[c].closeDefine()}else d(13,c)}));e[c].get(b)}function h(a,b){function c(a,b){B(b,function(b){a.push(b)})}function n(){var a=p.shift();a in k||(k[a]=!0,a in e&&(a=e[a].getDeps(),c(p,a)))}var k={},p=[];for(c(p,b);0<p.length;)n();return a in k}var l=!1,e={},q=[];return{requireModulesWithModuleBase:function(f,e,c){u(f)?a(f,function(a){for(var k=[],p=0;p<e.length;p++){var f=b(a,e[p]);if("string"===typeof f&&""!==
f)k.push(f);else{d(8,a+" -> "+e[p]);return}}g(k,c)}):d(9,f)},requireModules:g,requireOne:m,define:function(a,b){var c=D();if(!0!==l)null===c?w(49,""):w(49,D().getAttribute("src"));else{if(null!==c&&(c=c.getAttribute("src"),c in e)){e[c].setDefine(a,b);return}c=s.getActialLoading();u(c)?c in e?e[c].setDefine(a,b):d(46,c):q.push({deps:a,define:b})}}}}(),s=null,z=[],I=(new Date).getTime();t(window,"require",r,!1,27);t(window,"define",F,!1,28);t(r,"runnerBox",function(a){function b(a){x in a||(a[x]=m());
return a[x]}function g(){function a(){if(!0===b)for(;0<c.length;){var n=c.shift();setTimeout(n,0)}}var b=!1,c=[];return{on:function(b){c.push(b);a()},exec:function(){!1===b?b=!0:d(41);a()}}}function m(){var a=!1,b=null,c=g();return{onReady:function(a){c.on(function(){a(b)})},setAsRun:function(){!1===a?a=!0:d(44)},setValue:function(f){!0===a?(b=f,c.exec()):d(42)},isRun:function(){return a}}}function h(a,b){function c(a){setTimeout(function(){b(a)},0)}for(var d=[],f=0;f<a.length;f++)d.push(a[f]);for(f=
0;f<d.length;f++)c(d[f])}function l(a){function c(){for(var b=e(a,"*["+f+"]",f),d=[],p=null,k=0;k<b.length;k++)p=b[k],!0===h(p,g)&&d.push(p);return d}function d(a){if(q(a))return!0===b(a).isRun()?!0:!1;if("HTML"===a.tagName)return!0}function g(b){if(b===a)return!0;if(q(b))return!1}function h(a,b){function c(a){f++;if(200<f)return d(),!1;var p=b(a);return!0===p||!1===p?p:a.parentNode?c(a.parentNode):!1}function d(){var a=Error("Too much recursion");setTimeout(function(){throw a;},0)}var f=0;return c(a.parentNode)}
if(a===document||!0===h(a,d)){var l;l="function"!==typeof a.getAttribute?!1:u(a.getAttribute("data-run-module"));return l?!0===b(a).isRun()?c():[a]:c()}return[]}function e(a,b,c){function d(a){a=a.childNodes;for(var b=0;b<a.length;b++){var f=a[b],k=void 0;if(k=1===f.nodeType)k=f.getAttribute(c),k="string"===typeof k&&""!==k;k?e.push(f):d(f)}}function f(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b}a===document&&(a=document.documentElement);if("function"===typeof a.querySelectorAll)return f(a.querySelectorAll(b));
var e=[];d(a);return e}function q(a){a=a&&a.getAttribute(f);return"string"===typeof a&&""!==a}var f="data-run-module",x="runnerBoxElementProp"+(new Date).getTime(),c=function(){if("function"===typeof window.requestAnimationFrame)return window.requestAnimationFrame;for(var a=["ms","moz","webkit","o"],b=null,c=0;c<a.length;++c)if(b=window[a[c]+"RequestAnimationFrame"],"function"===typeof b)return b;return function(a){a()}}();return{runElement:function(e){function k(a){a=a&&a.getAttribute(f);return"string"===
typeof a&&""!==a?a:null}e=l(e);h(e,function(e){var g=k(e),h=g.split(".");if(2!==h.length)throw Error("irregulari contents of the attribute data-run-module: "+g);var n=h[0],l=h[1];a([n],function(a){c(function(){var c;if(q(e)&&!1===b(e).isRun())if(b(e).setAsRun(),a&&"function"===typeof a[l])e.setAttribute(f+"-isrun","1"),c=a[l](e,function(a){b(e).setValue(a)}),"undefined"!==typeof c&&(d(50,g),b(e).setValue(c));else throw c='No function "'+l+'" in module : '+n,e.setAttribute(f+"-isrun",c),Error(c);})})})},
whenRun:function(a,c){if(q(a))b(a).onReady(c);else d(43)}}}(r),!1,29);t(r.runnerBox,"runElement",r.runnerBox.runElement,!1,30);t(r.runnerBox,"whenRun",r.runnerBox.whenRun,!1,31);t(r,"getLogs",function(a){if(!0===a){window.console.group();for(a=0;a<z.length;a++){var b=z[a];window.console[b.type](b.time,b.num,b.caption)}window.console.groupEnd()}else{a=[];for(b=0;b<z.length;b++)a.push(z[b]);return a}},!1,32);t(r,"defined",function(a){return null===s?!1:s.isLoad(a)},!1,33);t(r,"toUrl",function(a){if(u(a))return s.resolvePath(a,
"",!0);d(26)},!0,35);t(F,"amd",{},!0,37);t(r,"isBrowser",!0,!0,38);t(r,"specified",function(a){return null!==s&&s.isSpecified?s.isSpecified(a):!1},!0,39);(function(a,b){function d(b){function e(){var a=b.getAttribute("data-amd-preload");return u(a)?a.split(","):[]}function c(){var a=b.getAttribute("data-timeout-start");return 0<a?a:2E3}var g=h(b);return null!==g?(m(a,g,e(),c()),!0):!1}function m(a,d,c,e){function k(){setTimeout(function(){v(48,"run timeout "+e);g()},e)}function g(){setTimeout(function(){0<
c.length&&b(c,function(){});b.runnerBox.runElement(document)},0)}a({paths:d});l(window,"load",function(){v(48,"window.load");g();setTimeout(function(){v(48,"window.load -> 10s");g()},1E4)});"complete"===document.readyState&&(v(48,"isComplete"),g());"loaded"===document.readyState&&(v(48,"isLoaded"),k());l(document,"DOMContentLoaded",function(){v(48,"DOMContentLoaded");k();l(document.getElementsByTagName("body")[0],"pageshow",function(){v(48,"body pageshow");g()})});l(document,"readystatechange",function(){var a=
"readystatechange - "+document.readyState;"complete"===document.readyState||"loaded"===document.readyState?(v(48,a+" - exec"),k()):v(48,a+" - noexec")})}function h(a){function b(a){var c=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;return"function"===typeof a.trim?a.trim():null===a?"":(a+"").replace(c,"")}var c=a.getAttribute("data-static-amd-map");if("string"===typeof c){if(""===c)return{}}else return null;if("undefined"!==typeof JSON&&"function"===typeof JSON.parse)return JSON.parse(c);a=/(,)|(\[|{)|(}|])|"(?:[^"\\\r\n]|\\["\\\/bfnrt]|\\u[\da-fA-F]{4})*"\s*:?|true|false|null|-?(?!0\d)\d+(?:\.\d+|)(?:[eE][+-]?\d+|)/g;
var d,e=null;return(c=b(c+""))&&!b(c.replace(a,function(a,b,c,f){d&&b&&(e=0);if(0===e)return a;d=c||b;e+=!f-!c;return""}))?Function("return "+c)():null}function l(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)}var e=D();if(null===e||!0!==d(e))for(var e=document.getElementsByTagName("script"),q=0;q<e.length&&!0!==d(e[q]);q++);})(function(a){null===s?s=K(a.paths):d(2.2)},r)})();

</script>
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="256x256" href="https://ocdn.eu/forbes/fav/apple/apple-touch-icon-180x180.png">

<link rel="icon" href="https://ocdn.eu/forbes/fav/favicon.ico">

<link rel="mask-icon" href="https://ocdn.eu/forbes/fav/apple/safari-pinned-tab.svg" color="#5bbad5">

<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="https://ocdn.eu/forbes/fav/apple/browserconfig.xml">
<meta name="theme-color" content="#000000">

<script>
    var pulse2EmbedConfig = pulse2EmbedConfig || {
        pulsevideo: {
            player: 'flowplayer',
            autoplay: true
        }
    };
    pulse2EmbedConfig.settings = {
        click2Activate: []
    };

    const isHomePage = window.complementaryData && window.complementaryData.isHomePage;

    if (!isHomePage) {
        (function(d, t, s, e, n) {
            (e = d.createElement(t)), (n = d.getElementsByTagName(t)[0]);
            e.async = 1;
            e.src = s;
            n.parentNode.insertBefore(e, n);
        })(document, 'script', 'https://ocdn.eu/forbes/static/js/floating_player_v3.8.0.min.js');


            window.addEventListener('load', function() {
                if (typeof FloatingVideoPlayer === 'function') {
                    var floatingPlayer = FloatingVideoPlayer({
                        backgroundImage : "https://ocdn.eu/forbes/images/forbesvideo.jpg",
                        offset: {
                            top: 50
                        }
                    });
                }
            });

    }
</script>






    <script>
        window.pp_gemius_identifier = 'd6ZLoM9MUNVnbSpqvFhn23YX76FBJqb_X9xJgfmcmv7.x7'
        window.pp_gemius_hit_identifier = 'd6ZLoM9MUNVnbSpqvFhn23YX76FBJqb_X9xJgfmcmv7.x7';
    </script>

<script>
    window.paidModel = {
        userHash: '',
        isLoggedIn: false,
        isPaying: false,
        terms: [],
        resources: []
    };

    function readCookie(name) {
        const s = encodeURIComponent(name) + '=';
        const array = document.cookie.split(';');
        for (var i in array) {
            var c = array[i];
            while (c.charAt(0) === ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(s) === 0) {
                return decodeURIComponent(c.substring(s.length, c.length));
            }
        }
        return undefined;
    }

    var cookie = readCookie('user_data');
    if (cookie) {
        try {
            var userData = JSON.parse(cookie);
            if (userData) {
                paidModel.userHash = userData.userHash;
                paidModel.isLoggedIn = true;
                paidModel.isPaying = userData.isPaying;
                paidModel.terms = userData.termIds;
                paidModel.resources = userData.resourceIds;
            }
        } catch(e) { }
    }

    adsNoBanner = false;
    reducedAdsNet = hasReducedAdsNet(paidModel.resources);
    onetAds = {
    "async": 1,
    "sgn_cookie": 0,
    "whitelist": 0,
    "keywords": [
        "new_ucs",
        "diamenty-forbesa",
        "diamenty-forbesa-2021",
        "mazowieckie",
        "wojewodztwo-mazowieckie",
        "ranking"
    ],
    "target": "RASP_FORBES/DIAMENTY",
    "DV": "RASP_FORBES/DIAMENTY",
    "kropka": {
        "DX": "PV,puls,vbbfems,2,a",
        "PU": "7030dff3-7ef1-4878-ade5-8086e115e79d"
    },
    "keyvalues": {
        "ci": "7030dff3-7ef1-4878-ade5-8086e115e79d",
        "structure": "detal"
    },
    "cmd": [],
    "adSlots": [],
    "mobile": 0,
    "autoslot": 1,
    "no_gemius": 1,
    "cookieInfo": 1,

In [72]:
from bs4 import BeautifulSoup
import re
import pandas as pd

In [91]:
soup = BeautifulSoup(req.text, 'html.parser')
div = soup.find('div',class_='tableWrapper')
divs = div.find_all('td')


forbes_dict = {'Firma':[],'Siedziba':[],'Zysk':[],'Średnia':[],'Branża':[],'Sprzedaż 2019':[]}
for div in divs:
    
    if str(div).find("Siedziba") != -1:
        forbes_dict['Siedziba'].append(div.text.strip())
    if str(div).find("Firma") != -1:
        forbes_dict['Firma'].append(div.text.strip())
    if str(div).find("Zysk") != -1:
        forbes_dict['Zysk'].append(div.text.strip())
    if str(div).find("Branża") != -1:
        forbes_dict['Branża'].append(div.text.strip())
    if str(div).find("Średnia") != -1:
        forbes_dict['Średnia'].append(div.text.strip())
    if str(div).find("Sprzedaż 2019") != -1:
        forbes_dict['Sprzedaż 2019'].append(div.text.strip())



data=pd.DataFrame(forbes_dict)

In [92]:
data

,Firma,Siedziba,Zysk,Średnia,Branża,Sprzedaż 2019
0,BRISTOL MYERS SQUIBB POLSKA SP. Z O.O.,Warszawa,"119,29","175,88",Hurtownie wyr. farmaceutycznych,"258,89"
1,TIME SA,Warszawa,"33,43","81,65",Pośrednictwo w sprzedaży miejsca na cele rekla...,"304,53"
2,ZAKŁAD DROBIARSKI SP. Z O.O.,Stasin,"26,91","80,57",Ubój i przetwórstwo drobiu,"499,59"
3,KORPORACJA KGL SA,Mościska,"12,7","75,43",Opakowania z tworzyw sztucznych,"384,57"
4,IBM POLSKA SP. Z O.O.,Warszawa,"156,57","63,38",Hurtownie komputerów i oprogramowania,"957,34"
...,...,...,...,...,...,...
80,MEDCOM SP. Z O.O.,Warszawa,"42,5","15,71",Urządzenia elektryczne,"320,67"
81,URZĄD DOZORU TECHNICZNEGO,Warszawa,"115,49","15,62",Urzędy władzy wykonawczej,"471,95"
82,CIRCLE K POLSKA SP. Z O.O.,Warszawa,"88,11","15,57",Stacje benzynowe,"5373,9"
83,WITTCHEN SA,Palmiry,"31,9","15,4",Sklepy obuwnicze,"284,04"
84,CARSERWIS SP. Z O.O.,Warszawa,"1,09","15,33",Sprzedawcy samochodów,"331,45"

In [93]:
data[data['Branża']=='Badania naukowe']

,Firma,Siedziba,Zysk,Średnia,Branża,Sprzedaż 2019
12,ASTRAZENECA PHARMA POLAND SP. Z O.O.,Warszawa,"46,44","40,29",Badania naukowe,"539,11"
38,NARODOWE CENTRUM BADAŃ JĄDROWYCH,Otwock,"46,69","24,44",Badania naukowe,"329,84"

In [97]:
data.iloc[5]

Firma            TRUMPF HUETTINGER SP. Z O.O.
Siedziba                             Zielonka
Zysk                                    71,85
Średnia                                 62,04
Branża              Systemy rozdziału energii
Sprzedaż 2019                          377,51
Name: 5, dtype: object

### json

In [94]:
x = [{i: j for i in range(5)} for j in range(10)]
x

[{0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 {0: 2, 1: 2, 2: 2, 3: 2, 4: 2},
 {0: 3, 1: 3, 2: 3, 3: 3, 4: 3},
 {0: 4, 1: 4, 2: 4, 3: 4, 4: 4},
 {0: 5, 1: 5, 2: 5, 3: 5, 4: 5},
 {0: 6, 1: 6, 2: 6, 3: 6, 4: 6},
 {0: 7, 1: 7, 2: 7, 3: 7, 4: 7},
 {0: 8, 1: 8, 2: 8, 3: 8, 4: 8},
 {0: 9, 1: 9, 2: 9, 3: 9, 4: 9}]

In [98]:
import json
json.dumps(x)

'[{"0": 0, "1": 0, "2": 0, "3": 0, "4": 0}, {"0": 1, "1": 1, "2": 1, "3": 1, "4": 1}, {"0": 2, "1": 2, "2": 2, "3": 2, "4": 2}, {"0": 3, "1": 3, "2": 3, "3": 3, "4": 3}, {"0": 4, "1": 4, "2": 4, "3": 4, "4": 4}, {"0": 5, "1": 5, "2": 5, "3": 5, "4": 5}, {"0": 6, "1": 6, "2": 6, "3": 6, "4": 6}, {"0": 7, "1": 7, "2": 7, "3": 7, "4": 7}, {"0": 8, "1": 8, "2": 8, "3": 8, "4": 8}, {"0": 9, "1": 9, "2": 9, "3": 9, "4": 9}]'

In [102]:
with open('test.json','w') as file:
    json.dump(x, file)

In [103]:
with open('test.json','r') as file:
    y = json.load(file)
    print(y)

[{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0}, {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}, {'0': 2, '1': 2, '2': 2, '3': 2, '4': 2}, {'0': 3, '1': 3, '2': 3, '3': 3, '4': 3}, {'0': 4, '1': 4, '2': 4, '3': 4, '4': 4}, {'0': 5, '1': 5, '2': 5, '3': 5, '4': 5}, {'0': 6, '1': 6, '2': 6, '3': 6, '4': 6}, {'0': 7, '1': 7, '2': 7, '3': 7, '4': 7}, {'0': 8, '1': 8, '2': 8, '3': 8, '4': 8}, {'0': 9, '1': 9, '2': 9, '3': 9, '4': 9}]

In [106]:
import gzip

with gzip.open('test.json.gzip','wt', encoding = 'utf-8') as file:
    json.dump(x, file)

In [107]:
with gzip.open('test.json.gzip','r') as file:
    y = json.load(file)
    print(y)

[{'0': 0, '1': 0, '2': 0, '3': 0, '4': 0}, {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}, {'0': 2, '1': 2, '2': 2, '3': 2, '4': 2}, {'0': 3, '1': 3, '2': 3, '3': 3, '4': 3}, {'0': 4, '1': 4, '2': 4, '3': 4, '4': 4}, {'0': 5, '1': 5, '2': 5, '3': 5, '4': 5}, {'0': 6, '1': 6, '2': 6, '3': 6, '4': 6}, {'0': 7, '1': 7, '2': 7, '3': 7, '4': 7}, {'0': 8, '1': 8, '2': 8, '3': 8, '4': 8}, {'0': 9, '1': 9, '2': 9, '3': 9, '4': 9}]